from .category_types import NodeCategory as NC

NODE_CAT_LABELS = {
	# Analysis/
	NC.MAXWELLSIM_ANALYSIS: 'Analysis',
	NC.MAXWELLSIM_ANALYSIS_MATH: 'Math',
	# Inputs/
	NC.MAXWELLSIM_INPUTS: 'Inputs',
	NC.MAXWELLSIM_INPUTS_SCENE: 'Scene',
	NC.MAXWELLSIM_INPUTS_CONSTANTS: 'Constants',
	NC.MAXWELLSIM_INPUTS_FILEIMPORTERS: 'File Importers',
	NC.MAXWELLSIM_INPUTS_WEBIMPORTERS: 'Web Importers',
	# Outputs/
	NC.MAXWELLSIM_OUTPUTS: 'Outputs',
	NC.MAXWELLSIM_OUTPUTS_FILEEXPORTERS: 'File Exporters',
	NC.MAXWELLSIM_OUTPUTS_WEBEXPORTERS: 'Web Exporters',
	# Sources/
	NC.MAXWELLSIM_SOURCES: 'Sources',
	NC.MAXWELLSIM_SOURCES_TEMPORALSHAPES: 'Temporal Shapes',
	# Mediums/
	NC.MAXWELLSIM_MEDIUMS: 'Mediums',
	NC.MAXWELLSIM_MEDIUMS_NONLINEARITIES: 'Non-Linearities',
	# Structures/
	NC.MAXWELLSIM_STRUCTURES: 'Structures',
	NC.MAXWELLSIM_STRUCTURES_PRIMITIVES: 'Primitives',
	# Bounds/
	NC.MAXWELLSIM_BOUNDS: 'Bounds',
	NC.MAXWELLSIM_BOUNDS_BOUNDCONDS: 'Conds',
	# Monitors/
	NC.MAXWELLSIM_MONITORS: 'Monitors',
	NC.MAXWELLSIM_MONITORS_PROJECTED: 'Projected',
	# Simulations/
	NC.MAXWELLSIM_SIMS: 'Simulations',
	NC.MAXWELLSIM_SIMS_SIMGRIDAXES: 'Sim Grid Axes',
	# Utilities/
	NC.MAXWELLSIM_UTILITIES: 'Utilities',
}
