####################
# - Project Config
####################
project:
  type: website
  output-dir: _site

format:
  html:
    toc: true

filters:
  - interlinks

interlinks:
  sources:
    numpy:
      url: https://numpy.org/doc/stable/
    matplotlib:
      url: https://matplotlib.org/stable/
    python:
      url: https://docs.python.org/3/

metadata-files:
  # Sidebar for /pydocs Paths
  - pydocs/_sidebar.yml

####################
# - Website Config
####################
website:
  title: "Blender Maxwell"
  description: "A Blender-based design and analysis tool for electromagnetic simulations"
  page-footer: "Copyright 2024, Sofus Albert Høgsbro Rose" 
  repo-url: https://github.com/so-rose/blender_maxwell/
  repo-actions: [issue]
  page-navigation: true
  navbar:
    background: primary
    pinned: true
    search: true
    left:
      - file: index.qmd
        text: Home
      - file: pydocs/index.qmd
        text: Reference
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/so-rose/blender_maxwell/
          - text: Report a Bug
            url:  https://github.com/so-rose/blender_maxwell/issues/new/choose

####################
# - Quartodoc Config
####################
quartodoc:
  # Output
  dir: pydocs
  sidebar: pydocs/_sidebar.yml

  # Python Package
  source_dir: ../src
  package: blender_maxwell
  parser: google

  # Style
  style: pkgdown
  title: "Blender Maxwell"

  # Options
  renderer:
    style: markdown
    #show_signature: true
    show_signature_annotations: false
    display_name: name
  options:
    #include_private: true
    include_empty: true
    include_attributes: true
    signature_name: "short"

  sections:
    ####################
    # - scripts
    ####################
    - title: "`scripts`"
      desc: Build/packaging scripts for developing and publishing the addon.
      package: scripts
      contents:
        - info
        - pack
        - dev
        - bl_delete_addon
        - bl_install_addon

    ####################
    # - bl_maxwell
    ####################
    - title: "`bl_maxwell`"
      desc: Root package for the addon.
      contents:
        - preferences
        - registration

    - subtitle: "`bl_maxwell.assets`"
      desc: Blender assets bundled w/Blender Maxwell
      contents:
        - assets
        - assets.import_geonodes

    - subtitle: "`bl_maxwell.nodeps`"
      desc: No-Dependency 
      contents:
        - operators

    - subtitle: "`bl_maxwell.utils`"
      desc: Utilities wo/shared global state.
      contents:
        - utils.analyze_geonodes
        - utils.blender_type_enum
        - utils.extra_sympy_units
        - utils.logger
        - utils.pydantic_sympy

    - subtitle: "`bl_maxwell.services`"
      desc: Utilities w/shared global state.
      contents:
        - services.tdcloud

    - subtitle: "`bl_maxwell.operators`"
      desc: General Blender operators.
      contents:
        - operators.bl_append
        - operators.connect_viewer

    ####################
    # - ..maxwell_sim_nodes
    ####################
    - title: "`..maxwell_sim_nodes`"
      desc: Maxwell Simulation Design/Viz Node Tree.
      package: blender_maxwell.node_trees.maxwell_sim_nodes
      contents:
        - bl_socket_map
        - categories
        - bl_cache
        - node_tree

    - subtitle: "`contracts`"
      desc: Constants and interfaces for identifying resources.
      package: blender_maxwell.node_trees.maxwell_sim_nodes.contracts
      contents:
        # General
        - flow_kinds
        - flow_kinds.FlowKind
        - flow_kinds.LazyValueFuncFlow
        - icons

        - tree_types

        # Managed Objects
        - mobj_types

        # Nodes
        - node_types
        - category_types
        - category_labels

        # Sockets
        - socket_types
        - socket_colors
        - bl_socket_types
        - bl_socket_desc_map
        - socket_units

        - unit_systems

    - subtitle: "`managed_objs`"
      desc: Maxwell Simulation Design/Viz Node Tree
      package: blender_maxwell.node_trees.maxwell_sim_nodes.managed_objs
      contents:
        - managed_bl_collection
        - managed_bl_empty
        - managed_bl_image
        - managed_bl_mesh
        - managed_bl_modifier

    ####################
    # - ..maxwell_sim_nodes.nodes
    ####################
    - title: "`...sockets`"
      desc: Maxwell Simulation Node Sockets
      package: blender_maxwell.node_trees.maxwell_sim_nodes.sockets
      contents:
        - base
        - scan_socket_defs

    ####################
    # - ..maxwell_sim_nodes.nodes
    ####################
    - title: "`...nodes`"
      desc: Maxwell Simulation Nodes
      package: blender_maxwell.node_trees.maxwell_sim_nodes.nodes
      contents:
        - base
        - events
