####################
# - Colors
####################
COLOR_SOCKET_SOURCE = (0.4, 0.4, 0.9, 1.0)
COLOR_SOCKET_MEDIUM = (1.0, 0.4, 0.2, 1.0)
COLOR_SOCKET_STRUCTURE = (0.2, 0.4, 0.8, 1.0)
COLOR_SOCKET_BOUND = (0.7, 0.8, 0.7, 1.0)
COLOR_SOCKET_FDTDSIM = (0.9, 0.9, 0.9, 1.0)


####################
# - Icons
####################
ICON_SIM = 'MOD_SIMPLEDEFORM'

ICON_SIM_SOURCE = 'FORCE_CHARGE'
ICON_SIM_MEDIUM = 'MATSHADERBALL'
ICON_SIM_STRUCTURE = 'OUTLINER_DATA_MESH'
ICON_SIM_BOUND = 'MOD_MESHDEFORM'
ICON_SIM_SIMULATION = ICON_SIM
